### ISSUE TITLE
The package for 2.2.0 fails to run

### ISSUE THREAD

**Issue by ygalblum** [artis3n/ansible_galaxy_collection#54] opened 2020-04-07 20:50 UTC
The Dockerfile tries to copy the package.json file (https://github.com/artis3n/ansible_galaxy_collection/blob/master/Dockerfile#L17) but it is not included in the package

**Comment by ygalblum** [comment] 2020-04-07 20:52
The logs for my action:
https://pipelines.actions.githubusercontent.com/MDfdAnDlcVSFnrJDuQuNz9Qjutp9NglV8i7FjXwUa0vyY8Q6uZ/_apis/pipelines/1/runs/2/signedlogcontent/3?urlExpires=2020-04-07T20%3A52%3A06.0655693Z&urlSigningMethod=HMACV1&urlSignature=4lNqdbap9wEVdqO9SUPKo1BaWKeCzHj4EF%2FoVUI6Eoc%3D

**Comment by artis3n** [comment] 2020-04-07 20:59
The URI for that logs link has expired, can you provide another link? That COPY line in the Dockerfile was updated in 2.1.0 The latest CI run (post-2.1.0, pre-2.2.0) builds the image with that COPY command:
![image](https://user-images.githubusercontent.com/6969296/78718780-df2d6600-78f0-11ea-8859-9bfff4077e6c.png)
https://github.com/artis3n/ansible_galaxy_collection/runs/562859243?check_suite_focus=true

Curious to see the error logs

**Comment by artis3n** [comment] 2020-04-07 21:04
Alternatively, you can try using a pre-built image in your workflow file with:

```yaml
- name: xxx
  uses: docker://artis3n/ansible_galaxy_collection:v2.2.0
```

https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-a-docker-hub-action

That would avoid the need to install the dependencies when your workflow is triggered - as long as you have connectivity to Docker Hub or some mirror.

**Comment by ygalblum** [comment] 2020-04-07 21:05
Please see the end of the log below. You can see the failure in step 7:

2020-04-07T20:44:18.5727792Z Step 6/9 : COPY dist/ dist/
2020-04-07T20:44:18.5734255Z  ---> Using cache
2020-04-07T20:44:18.5734584Z  ---> cb136b50b6e1
2020-04-07T20:44:18.5734703Z Step 7/9 : COPY package*.json ./
2020-04-07T20:44:18.5843006Z COPY failed: no source files were specified
2020-04-07T20:44:18.5971592Z ##[error]Docker build failed with exit code 1
2020-04-07T20:44:18.6004812Z Cleaning up orphan processes

**Comment by ygalblum** [comment] 2020-04-07 21:06
This is my action: https://github.com/ctera/ctera-ansible-collections/blob/master/.github/workflows/publish.yml

**Comment by artis3n** [comment] 2020-04-07 21:08
Thanks for the link to the action. I'll try to reproduce this and see what's going on. In the meantime, I suggest using the `docker://` syntax which will get your project running. The docker images are pinned to the specific `major.minor.patch`, instead of the `@v2` label, but are already built so you can just pull it and run.

**Comment by artis3n** [comment] 2020-04-07 21:27
Reproduced in: https://github.com/artis3n/test_issue_54/runs/568963586?check_suite_focus=true

**Comment by artis3n** [comment] 2020-04-07 22:38
Thanks for filing this! This has revealed a deeper issue that had not occurred before the new releases in the last couple days. See https://github.com/artis3n/ansible_galaxy_collection/pull/55#issuecomment-610642482 for details. I believe I resolved this issue you encounter in your log, but I am now facing this other thing in the fix.

**Comment by artis3n** [comment] 2020-04-10 23:54
Ok I believe this is now resolved in `v2.2.1`. I believe we have identified a bug with how GitHub Actions implement their default `WORKDIR` - see https://github.com/artis3n/ansible_galaxy_collection/pull/55/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR17 for more details on that. This issue will close once my 2.2.1 PR merges - please let me know if you still encounter an error on 2.2.1.

**Closed** 2020-04-11 00:09 UTC
Labels: In Progress, bug

**Comment by artis3n** [comment] 2020-04-11 00:12
Ok `2.2.1` is released. Since your workflow file uses `uses: artis3n/ansible_galaxy_collection@v2` you will pick up the new version when you next run your workflow.

**Comment by ygalblum** [comment] 2020-04-29 21:29
I've just used the updated version and it works perfectly, Thanks for the quick response and fix
